language: node_js
node_js:
  - 'node'

cache: yarn

jobs:
  include:
    - stage: Tests
      name: Lint
      script: yarn lint
    - name: Test
      script: yarn test
    - stage: release
      provider: script
      skip_cleanup: true
      script:
        - yarn run semantic-release
