language: node_js
node_js:
  - 'node'

cache: yarn

jobs:
  include:
    - stage: Tests
      name: Lint
      script: yarn lint
    - name: Test
      script: yarn test
    - stage: release
      branches:
        only:
          - master
      provider: script
      skip_cleanup: true
      script:
        - yarn lerna publish --github-release  --conventional-commits --yes
